// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/join": {
    params: {};
  };
  "/transfer/:code": {
    params: {
      "code": string;
    };
  };
  "/support": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/how-it-works": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/join" | "/transfer/:code" | "/support" | "/privacy" | "/how-it-works";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/join.tsx": {
    id: "routes/join";
    page: "/join";
  };
  "routes/transfer.tsx": {
    id: "routes/transfer";
    page: "/transfer/:code";
  };
  "routes/support.tsx": {
    id: "routes/support";
    page: "/support";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/how-it-works.tsx": {
    id: "routes/how-it-works";
    page: "/how-it-works";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/join": typeof import("./app/routes/join.tsx");
  "routes/transfer": typeof import("./app/routes/transfer.tsx");
  "routes/support": typeof import("./app/routes/support.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/how-it-works": typeof import("./app/routes/how-it-works.tsx");
};